### ISSUE TITLE
Handle stock transfers

### ISSUE THREAD

**Issue by adrianwb** [sussol/mobile#332]
Build Number: N/A

Description: If a customer invoice for a customer which happens to be another store is finalised in mobile, it should generate a supplier invoice in the customer store (which then gets synced back to the server)

Reproducible: Haven't checked yet - may not be an issue?

Reproduction Steps:

Comments:

**Comment by Chris-Petty** [comment]
http://bugs.msupply.org.nz/view.php?id=8292

**Comment by Chris-Petty** [comment]
I made a duplicate haha.

Description: 
Need to support selecting another store when making a customer invoice to enact a stock transfer. This is largely mSupply/server side changes off the top of my head. Stores need to be visible in customer list, server manages passing it along via sync.

Comments: 
Likely prerequisite to handling #402

**Comment by edmofro** [comment]
Stores will already be visible as customer on creating new invoice if they are visible in that store. Just server side changes pretty sure

**Comment by nmadruga** [comment]
I checked now using master version of mobile and 2 different stores running on Genymotion, using V2 of mSupply changes made by @adrianwb on https://github.com/sussol/msupply/pull/1321 for #8292 Matis Issue: http://bugs.msupply.org.nz/view.php?id=8292.

Tested: Create CI on 1st mobile store to 2nd mobile store. Added some items and Finalise it.
Result: SI appears on 3nd mobile store after both are sync, but not the lines of items.

Solution: Me and Andrei talked about what might be happening. This could be because the queue is only adding the transaction when it's empty (when first created), and the code on mobile doesn't put it back on the queue (after is finalised) because it is a duplication. In that case, we should now check if it was in the queue first, delete it and them add it as finalised at the end. 
I'll start doing this change on mobile now.

**Comment by adrianwb** [comment]
Hard to tell exactly where the problem lies, but here are some things to check...

on the desktop server:
- are both mobile stores configured correctly i.e. are they each transfer stores on the other sync site?
- does the CI in the sending store have any lines?
- does the SI in the receiving store have any lines?

and on mobile:
- is it removing existing identical sync records when it adds a new one to the queue?
- is it only finalising the CI *after* it has sent all the CI lines?

**Comment by andreievg** [comment]
This has been fixed Yesterday, Nicole implemented changes as per our e-mail chain. And for V3 we can all assume that finalised Transaction/Requisition sync records, will be in the sync queue after their contents. And Mobile assumes it's fine to send sync record type 'update' even if 'create' has not been sent for that particular recordType and recordID..

Extra: https://bugs.msupply.org.nz/view.php?id=8293
