### ISSUE TITLE
Stock lines with no batch invisible

### ISSUE THREAD

**Issue by adrianwb** [sussol/mobile#403]
Build Number: 30

Description: Stock lines with no batch are not showing up on mobile

Reproducible: Yes

Reproduction Steps: On demo.msupply.org server, compare SI's for Mobile Store 1 on server vs mobile

Comments: Eek! Problem found by Andrew Davies while trying to setup demo for him (Medical Action Myanmar)

**Comment by adrianwb** [comment]
Connection details:
    Primary Server URL: https://demo.msupply.org:2048
    Sync Site Name: MobileUser1
    Sync Site Password: MobileTest1
login with:
    User Name: MobileUser1
    Password: MobilePass1

**Comment by Chris-Petty** [comment]
@adrianwb I'm looking into this on the mobile side at this moment. I wrote that line 2 hours ago.

I didn't get to go too deep debugging due to compilation bugs thanks to some dev tools being a pain, but looking at the code I think it's sync doing something funky on either end (I suspect mobile but I need to do some logging).

**Comment by andreievg** [comment]
Issue was fixed since build 30.
mSupply mobiles used to check all fields exist and not empty. A couple of month ago a change was committed allowing to have empty fields.
Tested on 4.4+ Androids, changes, both locally and on demo.msupply.org

We are trying a sprint to finish 1.2 changes asap so we can have a new release version for those currently effected (if not done by the end of the week, will release 1.0.31).
