### ISSUE TITLE
Adding Master List to Customer Invoice shouldn't add items with no stock

### ISSUE THREAD

**Issue by Chris-Petty** [sussol/mobile#428]
Build Number: 1.1.1

Description: Currently when adding a master list to a customer invoice, it adds all items including those with no stock. These are immediately redundant and get in the way.

Solution:
- When adding master list items in the function for the button, just ignore those with no stock.
- Add a new button "Remove stockouts"

**Comment by GaryWilletts** [comment]
Not sure this is a good idea to change. To the user it looks as though some of the items haven't been added to the customer invoice for no good reason. Either leave it as is or, at the least, needs a popup message to tell the user some items have been left off because of no stock.

I would argue that the right thing to do would be to leave it as it is now and the user can delete lines with no stock. Makes it clear what they've run out of, doesn't hide stockouts.

**Comment by Chris-Petty** [comment]
So does the second suggestion of having a "Remove Stockouts" button fit with that idea?

**Comment by Chris-Petty** [comment]
Closing on account of Gary's input. Should help users think "hey, need more of...".
