### ISSUE TITLE
Bugsnag: TransactionBatch.numberOfPacks must be of type: number

### ISSUE THREAD

**Issue by sussol-invoices** [sussol/mobile#540]
## Error in mSupply Mobile

**Error** in **index.android.bundle:733**
TransactionBatch.numberOfPacks must be of type: number

[View on Bugsnag](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/59dd87b392bd570017522854?event_id=59dd87b392bd570017522853&i=gh&m=ci)

## Stacktrace

    index.android.bundle:733 - 

[View full stacktrace](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/59dd87b392bd570017522854?event_id=59dd87b392bd570017522853&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by Chris-Petty** [comment]
Replicated:
![image](https://user-images.githubusercontent.com/7684221/32200401-49ca3d6c-be36-11e7-9b51-68c87fbd784c.png)

Steps:
1. Create a new supplier invoice
2. Add an item
3. select the quantity field
4. Clear the value (so that it is an empty string)
5. Press enter/change focus so that the field tries to save to realm.

This likely tries to parse an empty string as an integer, giving NaN. This fails to be written into realm, throwing RSoD as above.

**Comment by sussol-invoices** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Error** in **index.android.bundle:733**](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/59dd87b392bd570017522854?event_id=59ffbc9b146cec0018a2053b&i=gh&m=ra)

**Comment by Chris-Petty** [comment]
Fixed in #554. Old versions will continue throwing. Deleted issue on bugsnag.
